

[window]

decorations = "none"

startup_mode = "Maximized"

padding.x = 2
padding.y = 2

[font]

normal.family = "sleekspace"
bold.family = "sleekspace"
italic.family = "sleekspace"
bold_italic.family = "sleekspace"


size = 12.0

[colors]

[colors.primary]
background = "#ffffea"  # Light cream background
foreground = "#000000"  # Black text


[colors.cursor]
text = "#ffffff"        # White cursor text
cursor = "#000000"      # Black cursor


[colors.selection]
text = "#000000"        # Black selected text
background = "#b2b2b2"  # Light gray selection background


[colors.normal]
black = "#000000"       # Black
red = "#cc0000"         # Dark red
green = "#00aa00"       # Dark green  
yellow = "#aa5500"      # Brown/orange
blue = "#0000cc"        # Dark blue
magenta = "#aa00aa"     # Dark magenta
cyan = "#00aaaa"        # Dark cyan
white = "#aaaaaa"       # Light gray


[colors.bright]
black = "#555555"       # Dark gray
red = "#ff5555"         # Light red
green = "#55ff55"       # Light green
yellow = "#ffff55"      # Light yellow
blue = "#5555ff"        # Light blue
magenta = "#ff55ff"     # Light magenta
cyan = "#55ffff"        # Light cyan
white = "#ffffff"       # White

[scrolling]

history = 10000
multiplier = 3

[cursor]

style.shape = "Block"
style.blinking = "Never"

[terminal]

shell.program = "/bin/bash"

[keyboard]

bindings = [
    # Scroll up/down
    { key = "PageUp", mods = "Shift", action = "ScrollPageUp" },
    { key = "PageDown", mods = "Shift", action = "ScrollPageDown" },
    
    # Copy/paste (Plan 9 uses middle mouse, but we'll use standard keys)
    { key = "C", mods = "Control|Shift", action = "Copy" },
    { key = "V", mods = "Control|Shift", action = "Paste" },
    
    # Font size adjustment
    { key = "Plus", mods = "Control", action = "IncreaseFontSize" },
    { key = "Minus", mods = "Control", action = "DecreaseFontSize" },
    { key = "Key0", mods = "Control", action = "ResetFontSize" },
]

[mouse]

hide_when_typing = false


[selection]

save_to_clipboard = true
